# Generated by Django 4.0.3 on 2022-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('num', models.FloatField()),
                ('den', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
