# Generated by Django 4.0.6 on 2022-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0003_alter_organizationalstructureoffice_options'),
        ('detection_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='structure',
            field=models.ForeignKey(limit_choices_to={'is_internal': True}, on_delete=django.db.models.deletion.PROTECT, to='organizational_area.organizationalstructure'),
        ),
    ]
