# Generated by Django 4.0.6 on 2022-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0002_alter_detection_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='detaction_date',
            new_name='detection_date',
        ),
        migrations.AddField(
            model_name='detection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
