# Generated by Django 4.0.6 on 2022-07-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0003_rename_detaction_date_detection_detection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='code',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='detection_management.detectioncode'),
        ),
    ]
