# Generated by Django 4.0.6 on 2022-07-28 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0005_alter_detection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='den',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detection',
            name='num',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detection',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
