# Generated by Django 4.0.6 on 2022-07-28 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0006_alter_detection_den_alter_detection_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='den',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
