# Generated by Django 4.0.6 on 2022-07-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0007_alter_detection_den'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['code', '-reference_date']},
        ),
    ]
