# Generated by Django 4.1 on 2022-08-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0003_alter_organizationalstructureoffice_options"),
        ("detection_management", "0008_alter_detection_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureDetectionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection_management.detectioncode",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        limit_choices_to={"is_internal": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizational_area.organizationalstructure",
                    ),
                ),
            ],
        ),
    ]
