# Generated by Django 4.1 on 2022-11-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0003_alter_organizationalstructureoffice_options"),
        ("detection_management", "0009_structuredetectioncode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredetectioncode",
            name="structure",
            field=models.ForeignKey(
                limit_choices_to={"is_internal": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="organizational_area.organizationalstructure",
            ),
        ),
    ]
