# Generated by Django 5.1.4 on 2025-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_management', '0010_alter_structuredetectioncode_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectioncode',
            name='description',
            field=models.CharField(max_length=254),
        ),
    ]
