# Generated by Django 4.0.2 on 2022-02-05 08:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0003_auto_20190226_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=django_countries.fields.CountryField(
                blank=True, max_length=30, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
