# Generated by Django 4.0 on 2022-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0004_alter_user_id_alter_user_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(
                max_length=16, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Cognome'),
        ),
    ]
