# Generated by Django 4.0 on 2022-03-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0005_alter_user_codice_fiscale_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name',
                                  'username'], 'verbose_name_plural': 'Utenti UNICAL'},
        ),
    ]
