# Generated by Django 4.0 on 2022-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0007_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(
                max_length=16, unique=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
