# Generated by Django 5.0.3 on 2024-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0010_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_user_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo aggiornamento manuale dei dati'),
        ),
    ]
