# Generated by Django 5.1.3 on 2024-12-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0013_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('O', 'Altro')], max_length=12, null=True, verbose_name='Genere'),
        ),
    ]
