# Generated by Django 5.1.3 on 2024-12-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='intermediate_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='intermediate_validation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
