# Generated by Django 5.1.3 on 2024-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0002_alter_publicengagementevent_intermediate_taken_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementevent',
            name='to_validate',
            field=models.BooleanField(default=False),
        ),
    ]
