# Generated by Django 5.1.3 on 2024-12-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0003_publicengagementevent_to_validate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicengagementeventdata',
            name='is_active',
        ),
    ]
