# Generated by Django 5.1.3 on 2024-12-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0004_remove_publicengagementeventdata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='promo_channel',
            field=models.ManyToManyField(blank=True, limit_choices_to={
                                         'is_active': True}, null=True, to='public_engagement_monitoring.publicengagementeventpromochannel'),
        ),
    ]
