# Generated by Django 5.1.3 on 2024-12-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0005_alter_publicengagementeventdata_promo_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='data', to='public_engagement_monitoring.publicengagementevent'),
        ),
    ]
