# Generated by Django 5.1.3 on 2024-12-19 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0005_alter_organizationalstructureoffice_is_active'),
        ('public_engagement_monitoring',
         '0006_alter_publicengagementeventdata_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='data', to='public_engagement_monitoring.publicengagementevent'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='promo_channel',
            field=models.ManyToManyField(blank=True, limit_choices_to={
                                         'is_active': True}, to='public_engagement_monitoring.publicengagementeventpromochannel'),
        ),
        migrations.CreateModel(
            name='PublicEngagementEventCollaboratorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicEngagementEventScientificArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicEngagementEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('participants', models.IntegerField(default=0)),
                ('budget', models.FloatField()),
                ('monitoring_activity', models.BooleanField(default=False)),
                ('impact_evaluation', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('collaborator_type', models.ManyToManyField(limit_choices_to={
                 'is_active': True}, to='public_engagement_monitoring.publicengagementeventcollaboratortype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='report', to='public_engagement_monitoring.publicengagementevent')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('other_structure', models.ManyToManyField(limit_choices_to={
                 'is_active': True, 'is_internal': True, 'is_public_engagement_enabled': True}, to='organizational_area.organizationalstructure')),
                ('scientific_area', models.ManyToManyField(limit_choices_to={
                 'is_active': True}, to='public_engagement_monitoring.publicengagementeventscientificarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
