# Generated by Django 5.1.3 on 2024-12-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0008_rename_referent_organizational_structure_publicengagementevent_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='final_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='intermediate_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
