# Generated by Django 5.1.3 on 2024-12-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0010_rename_intermediate_notes_publicengagementevent_operator_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicengagementevent',
            old_name='final_notes',
            new_name='manager_notes',
        ),
        migrations.RenameField(
            model_name='publicengagementevent',
            old_name='final_taken_date',
            new_name='manager_taken_date',
        ),
        migrations.RenameField(
            model_name='publicengagementevent',
            old_name='final_validation_date',
            new_name='manager_validation_date',
        ),
        migrations.RenameField(
            model_name='publicengagementevent',
            old_name='final_validation_success',
            new_name='manager_validation_success',
        ),
    ]
