# Generated by Django 5.1.3 on 2024-12-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0011_rename_final_notes_publicengagementevent_manager_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementevent',
            name='manager_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='manager_taken_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicengagementevent',
            name='operator_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='operator_taken_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
