# Generated by Django 5.1.3 on 2024-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0012_publicengagementevent_manager_taken_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_taken_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
