# Generated by Django 5.1.3 on 2024-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0013_alter_publicengagementevent_operator_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
