# Generated by Django 5.1.4 on 2025-01-09 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring',
         '0015_alter_publicengagementeventdata_promo_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementevent',
            name='manager_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='manager_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicengagementevent',
            name='operator_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='operator_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicengagementevent',
            name='validation_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
