# Generated by Django 5.1.4 on 2025-01-17 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0019_alter_publicengagementevent_referent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_taken_by', to=settings.AUTH_USER_MODEL, verbose_name='Presa in carico da operatore'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_taken_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data presa in carico operatore'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data validazione operatore'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='operator_validation_success',
            field=models.BooleanField(default=False, verbose_name='Esito positivo validazione operatore'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='validation_request_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_request_by', to=settings.AUTH_USER_MODEL, verbose_name='Utente richiesta di validazione'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='validation_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data richiesta di validazione'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_scoped',
            field=models.BooleanField(default=False, verbose_name='Si tratta di un’attività collegata a un progetto o a una iniziativa più ampia?'),
        ),
    ]
