# Generated by Django 5.1.4 on 2025-01-22 11:30

import django.db.models.deletion
import public_engagement_monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0005_alter_organizationalstructureoffice_is_active'),
        ('public_engagement_monitoring', '0024_rename_validation_request_date_publicengagementevent_evaluation_request_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicengagementeventdata',
            options={'verbose_name': 'Event data', 'verbose_name_plural': 'Event data records'},
        ),
        migrations.AlterModelOptions(
            name='publicengagementeventreport',
            options={'verbose_name': 'Event monitoring', 'verbose_name_plural': 'Event monitoring records'},
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='end',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_referent', to=settings.AUTH_USER_MODEL, verbose_name='Referent'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='structure',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_internal': True, 'is_public_engagement_enabled': True}, on_delete=django.db.models.deletion.PROTECT, to='organizational_area.organizationalstructure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='event_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='public_engagement_monitoring.publicengagementeventtype', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='geographical_dimension',
            field=models.CharField(choices=[('Internazionale', 'International'), ('Nazionale', 'National'), ('Regionale', 'Regional'), ('Locale', 'Local')], default='', max_length=14, verbose_name='Geographical dimension'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='method_of_execution',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='public_engagement_monitoring.publicengagementeventmethodofexecution', verbose_name='Execution method'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='organizing_subject',
            field=models.CharField(choices=[('UniCal', 'University of Calabria (University, Department, or other structure)'), ('Altra università', 'Another university'), ('Altro ente pubblico', 'Another public entity'), ('Ente privato', 'Private entity')], default='', max_length=20, verbose_name='Main organizing entity of the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='other_recipients',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other recipients'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='patronage_requested',
            field=models.BooleanField(default=False, verbose_name='Request for the patronage of the Department/Center for the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Other UNICAL staff members involved in organizing/executing the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to=public_engagement_monitoring.models._poster_directory_path, verbose_name='Poster attached'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_scoped',
            field=models.BooleanField(default=False, verbose_name='Is this activity linked to a project or a broader initiative?'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='promo_channel',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventpromochannel', verbose_name='Request for the initiative to be promoted through the following institutional communication channels'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='promo_tool',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventpromotool', verbose_name='Request to use the Department/Center’s name and/or logo in the following communication tools'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='recipient',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventrecipient', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='target',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventtarget', verbose_name='Sustainable Development Goals (SDGs)'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='budget',
            field=models.FloatField(verbose_name='Total budget (in Euro)'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='collaborator_type',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventcollaboratortype', verbose_name='Which collaborators were involved in organizing/managing the initiative?'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='impact_evaluation',
            field=models.BooleanField(default=False, verbose_name='Is the initiative accompanied by an impact evaluation plan?'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='monitoring_activity',
            field=models.BooleanField(default=False, verbose_name='Is the initiative accompanied by monitoring activities (e.g., collection of information on activities, attendance, satisfaction, etc.)?'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='other_structure',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'is_internal': True, 'is_public_engagement_enabled': True}, to='organizational_area.organizationalstructure', verbose_name='Which other UNICAL structures (Departments or Centers) collaborated on this initiative?'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='participants',
            field=models.IntegerField(default=0, verbose_name='Non-academic audience participating in the initiative or reached via web/social resources, or outreach publications'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='scientific_area',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventscientificarea', verbose_name='Scientific areas'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Initiative’s website'),
        ),
    ]
