# Generated by Django 5.1.4 on 2025-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0025_alter_publicengagementeventdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicengagementeventscientificarea',
            name='name',
        ),
        migrations.AlterField(
            model_name='publicengagementevent',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='Event title'),
        ),
    ]
