# Generated by Django 5.1.4 on 2025-02-12 15:22

import public_engagement_monitoring.models
import public_engagement_monitoring.validators
import template.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0027_remove_publicengagementevent_manager_evaluated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to=public_engagement_monitoring.models._poster_directory_path, validators=[public_engagement_monitoring.validators.validate_poster_extension, template.validators.validate_file_size], verbose_name='Poster attached'),
        ),
    ]
