# Generated by Django 5.1.4 on 2025-02-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0028_alter_publicengagementeventdata_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='public_engagement_monitoring.publicengagementevent'),
        ),
    ]
