# Generated by Django 5.1.4 on 2025-02-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0029_alter_publicengagementeventdata_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicengagementeventdata',
            name='project_scoped',
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='public_engagement_monitoring.publicengagementevent', verbose_name='Is this activity linked to a project or a broader initiative?'),
        ),
    ]
