# Generated by Django 5.1.4 on 2025-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0006_alter_organizationalstructure_options'),
        ('public_engagement_monitoring', '0030_remove_publicengagementeventdata_project_scoped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventdata',
            name='structures',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'is_internal': True, 'is_public_engagement_enabled': True}, to='organizational_area.organizationalstructure', verbose_name='Other UNICAL structures involved in organizing/executing the initiative'),
        ),
    ]
