# Generated by Django 5.1.4 on 2025-02-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0032_alter_publicengagementeventdata_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicengagementeventdata',
            old_name='person',
            new_name='involved_personnel',
        ),
        migrations.RenameField(
            model_name='publicengagementeventdata',
            old_name='structures',
            new_name='involved_structure',
        ),
    ]
