# Generated by Django 5.1.4 on 2025-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0034_publicengagementeventpromochannelcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventcollaboratortype',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='other_recipients',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Other recipients'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventmethodofexecution',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventpromochannel',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventpromotool',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventrecipient',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventscientificarea',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicengagementeventtarget',
            name='description',
            field=models.CharField(max_length=254),
        ),
    ]
