# Generated by Django 5.1.4 on 2025-02-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0007_alter_organizationalstructure_banner_and_more'),
        ('public_engagement_monitoring', '0035_alter_publicengagementeventcollaboratortype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventpromochannelcontact',
            name='structure',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure', verbose_name='Structure'),
        ),
    ]
