# Generated by Django 5.1.4 on 2025-03-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0037_publicengagementeventpromochannel_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='public_engagement_monitoring.publicengagementevent', verbose_name='If the event is linked to a larger project, indicate which one'),
        ),
    ]
