# Generated by Django 5.1.4 on 2025-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0038_alter_publicengagementeventdata_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='collaborator_type',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='public_engagement_monitoring.publicengagementeventcollaboratortype', verbose_name='Which collaborators were involved in organizing/managing the initiative?'),
        ),
    ]
