# Generated by Django 5.1.7 on 2025-03-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_engagement_monitoring', '0042_alter_publicengagementeventdata_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='participants',
            field=models.IntegerField(verbose_name='Non-academic audience participating in the initiative or reached via web/social resources, or outreach publications'),
        ),
    ]
