# Generated by Django 4.1 on 2022-11-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management", "0004_publicengagement_objective_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicengagement",
            old_name="object",
            new_name="subject",
        ),
    ]
