# Generated by Django 4.1 on 2022-11-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management",
         "0005_rename_object_publicengagement_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicengagement",
            old_name="objective",
            new_name="goal",
        ),
    ]
