# Generated by Django 4.1 on 2022-11-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0001_initial"),
        ("public_engagement_management",
         "0006_rename_objective_publicengagement_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicengagementpartner",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organizational_area.organizationalstructure",
            ),
        ),
    ]
