# Generated by Django 4.1 on 2022-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management", "0009_alter_publicengagementpartner_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicengagement",
            name="requirements_one",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="publicengagement",
            name="requirements_three",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="publicengagement",
            name="requirements_two",
            field=models.BooleanField(default=False),
        ),
    ]
