# Generated by Django 4.1 on 2022-12-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public_engagement_management",
            "0010_alter_publicengagement_requirements_one_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicengagement",
            name="subject",
            field=models.TextField(),
        ),
    ]
