# Generated by Django 4.1.3 on 2022-12-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management", "0011_alter_publicengagement_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_type", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="PublicEngagementGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_engagement_management.goal",
                    ),
                ),
                (
                    "public_engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_engagement_management.publicengagement",
                    ),
                ),
            ],
            options={
                "unique_together": {("public_engagement", "goal")},
            },
        ),
    ]
