# Generated by Django 4.1.3 on 2022-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management", "0012_goal_publicengagementgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicengagement",
            name="goal",
        ),
    ]
