# Generated by Django 4.1.3 on 2022-12-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_engagement_management", "0013_remove_publicengagement_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicengagement",
            name="note",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="publicengagement",
            name="subject",
            field=models.TextField(max_length=500),
        ),
    ]
