# Generated by Django 4.0 on 2022-03-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unical_accounts', '0004_alter_user_id_alter_user_place_of_birth'),
        ('organizational_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('didactic_hour', models.PositiveIntegerField()),
                ('effective_days', models.PositiveIntegerField()),
                ('from_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='from_structure', to='organizational_area.organizationalstructure')),
                ('role', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='visiting_management.role')),
                ('to_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='to_structure', to='organizational_area.organizationalstructure')),
                ('visitor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='unical_accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='VisitingCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('collab', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='visiting_management.collaboration')),
                ('visiting', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='visiting_management.visiting')),
            ],
            options={
                'unique_together': {('visiting', 'collab')},
            },
        ),
    ]
