# Generated by Django 4.0 on 2022-03-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0007_user_created_by'),
        ('visiting_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='visitor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='unical_accounts.user'),
        ),
    ]
