# Generated by Django 4.0 on 2022-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0002_alter_visiting_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiting',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
