# Generated by Django 4.0 on 2022-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0003_visiting_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
