# Generated by Django 4.0 on 2022-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0004_alter_visiting_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='start_date',
            field=models.DateField(),
        ),
    ]
