# Generated by Django 4.0 on 2022-03-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0006_alter_visiting_end_date_alter_visiting_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiting',
            old_name='external',
            new_name='mission',
        ),
    ]
