# Generated by Django 4.0 on 2022-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0007_rename_external_visiting_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='start_date',
            field=models.DateField(),
        ),
    ]
