# Generated by Django 4.0.3 on 2022-04-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0012_visiting_created_visiting_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingcollaboration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visitingcollaboration',
            name='modified_by',
        ),
    ]
