# Generated by Django 4.1 on 2022-12-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizational_area",
            "0004_organizationalstructure_is_public_engagement_enabled_and_more",
        ),
        (
            "visiting_management",
            "0013_remove_visitingcollaboration_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visiting",
            name="from_structure",
            field=models.ForeignKey(
                limit_choices_to={"is_visiting_enabled": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_structure",
                to="organizational_area.organizationalstructure",
            ),
        ),
        migrations.AlterField(
            model_name="visiting",
            name="to_structure",
            field=models.ForeignKey(
                limit_choices_to={"is_visiting_enabled": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_structure",
                to="organizational_area.organizationalstructure",
            ),
        ),
    ]
