# Generated by Django 5.1.7 on 2026-04-30 13:39

import template.validators
import visiting_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0016_alter_collaboration_collab_type_alter_role_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiting',
            name='document',
            field=models.FileField(null=True, upload_to=visiting_management.models.visiting_doc_path, validators=[template.validators.validate_file_extension, template.validators.validate_file_size]),
        ),
    ]
