# Generated by Django 5.1.7 on 2026-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0017_visiting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiting',
            name='in_person',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
