# Generated by Django 5.1.7 on 2026-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_management', '0018_visiting_in_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='in_person',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
