# Generated by Django 4.0.3 on 2022-04-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructure',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
