# Generated by Django 4.1 on 2022-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0003_alter_organizationalstructureoffice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalstructure",
            name="is_public_engagement_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationalstructure",
            name="is_visiting_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
