# Generated by Django 4.1 on 2022-12-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizational_area",
            "0004_organizationalstructure_is_public_engagement_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationalstructureoffice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
