# Generated by Django 5.1.4 on 2025-02-18 14:26

import django.core.validators
import organizational_area.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0006_alter_organizationalstructure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='banner',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=organizational_area.models._logo_upload),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='name',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Lo slug deve contenere almeno un carattere alfabetico', regex='^(?=.*[a-zA-Z])')]),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='unique_code',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructurelocation',
            name='description_short',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructureoffice',
            name='slug',
            field=models.SlugField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organizationalstructureofficelocation',
            name='description_short',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
